### ISSUE TITLE
Diagnosing "Something is wrong with your metadata at position NaN and line 1"

### ISSUE THREAD

**Issue by wgoldie** [msfeldstein/interactive-shader-format-js#17]
https://github.com/msfeldstein/interactive-shader-format-js/blob/7f84e3a3acf52c0f7777ebac864b86c82c84bff8/src/MetadataExtractor.js#L18

This function doesn't appear to be portable - the error message that JSON.parse spits out isn't standardized.

In Chromium I get `"Unexpected token a in JSON at position 175"` which results in the correct behavior.

In Firefox I get `"JSON.parse: expected double-quoted property name at line 37 column 30 of the JSON data"`. Here the attempt to extract the position fails.

**Comment by msfeldstein** [comment]
looks like we just need to update the pattern matching?  I can look at this over the weekend probably, happy to accept pull requests as well

**Comment by wgoldie** [comment]
The issue is that `JSON.parse` can throw a `SyntaxError` with an arbitrary message. Different browsers/environments will have different error messages. I see a couple of options:

1. We can try to identify the messages of different browser/runtime vendors and match against them, and fail gracefully otherwise. Unfortunately it seems that the useful `SyntaxError.prototype.lineNumber` property is not implemented by anyone besides Firefox ([according to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError))

2. We could also use a library for JSON parsing that will reliably emit error locations. [`jsonlint`](https://github.com/zaach/jsonlint) seems like a good lightweight option.

Happy to write a PR on either of these tomorrow or over the weekend but I'm not sure which is better from your perspective.

**Comment by msfeldstein** [comment]
The library doesn't look huge maybe that's the best bet. Would be nice to
have reliable parsing. Since you're working on the site I leave the choice
to you.
