### ISSUE TITLE
Add UMD/global/worker scope build

### ISSUE THREAD

**Issue by 2xAA** [msfeldstein/interactive-shader-format-js#20]
Adding a UMD/global/worker scope build of the library (i.e. a version of the ISF library which doesn't rely on the DOM/window being present) will allow use of the ISF library in a WebWorker, allowing OffscreenCanvas support.

This is important for OffscreenCanvas related performance gains and will extend the functionality of this library greatly and close #16.

Either we can find a way to support this using browserify or alternatively I can easily set up a compatible Webpack build which can build to multiple targets.

I don't have a lot of Browserify experience and my attempt of building the library with the `--standalone` Browserify flag didn't work. Math.JS seems to be a problem.

Are we able to remove Math.JS? #3.

**Comment by msfeldstein** [comment]
i have no particular love for browserify for production stuff, and if you're good at webpack i would be fine moving away from it.

if there's a simpler way to do the math needed for parsing the buffer sizes we should remove that too.
