### ISSUE TITLE
Buffer Error

### ISSUE THREAD

**Issue by 2xAA** [msfeldstein/interactive-shader-format-js#9]
I've followed the simple example of the README, but buffers don't seem to be working.
This is probably just in my implementation, however as there are no examples for me to check against, it's very difficult to diagnose if the problem is my implementation or the library itself.

More simple shaders without buffers seem to work fine.

I've tried using this demo shader (the website looks like it's using this library):
https://www.interactiveshaderformat.com/sketches/326

But I get:

```
[.Offscreen-For-WebGL-0000029B7DE2FB20]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
localhost/:1 [.Offscreen-For-WebGL-0000029B7DE2FB20]RENDER WARNING: texture bound to texture unit 1 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
localhost/:1 [.Offscreen-For-WebGL-0000029B7DE2FB20]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawArrays: framebuffer incomplete
```

The first error seems strange as I'm supplying a suitable canvas to the draw function.
GLSL (es300 at least) doesn't much care about power of two anymore I thought? Unless framebuffers are different? I'm not used them much in the past.

The second error I assume is linked to the first, however I don't know for sure.

Thanks for your work on this library, I'd love to contribute at some point.

**Comment by 2xAA** [comment]
It's an implementation issue, I'll diagnose and fix myself.
Sorry for the non issue.

**Comment by msfeldstein** [comment]
@2xAA thanks for looking into all this, was out on honeymoon but should be more responsive now!

**Comment by 2xAA** [comment]
@msfeldstein No problem and congratulations!
The PR fixing out of DOM destinations fixed this issue.

I've also switched to a webpack build process on my fork, not sure if that's of any interest to you? I'll make a PR if so.
However, I accidentally nerfed some tests on that fork, so I'll fix those soon.

**Comment by msfeldstein** [comment]
i'll try a couple things with your branch but i'm guessing that using webpack vs babel directly would be useful to people using it in real projects
